### ISSUE TITLE
include order

### ISSUE THREAD

**Issue by tvaneerd** [kmhofmann/cpp_coding_guidelines#2]
I think your include order is precisely backwards.

If you instead order it the opposite way, you will more easily find that `bar/Gadget.hpp` is missing `#include <vector>`, for example.

What are the benefits of your order?

**Comment by kmhofmann** [comment]
You are completely right. The rationale for the previous order was simply to establish a (and follow existing) convention.
I have followed the reverse order for quite a while now, but had forgotten to update the guidelines.
